global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  # ---------------------------------------
  # FOODFAST PROJECT
  # ---------------------------------------
  - job_name: "foodfast"
    metrics_path: "/metrics"
    scheme: "https"
    static_configs:
      - targets:
          - "foodfast-production.up.railway.app"
        labels:
          namespace: "foodfast"
          project: "foodfast"

  # ---------------------------------------
  # FOG PROJECT (SGU ĐỒ ÁN KTPM)
  # ---------------------------------------
  - job_name: "fog"
    metrics_path: "/metrics"
    scheme: "https"
    static_configs:
      - targets:
          - "sgu25doanktpm-production.up.railway.app"
        labels:
          namespace: "fog"
          project: "fog"

